sudo: required

services:
- docker

language: node_js
node_js:
  - lts/*

cache: yarn

script:
  echo "Tests were run previously"

deploy:
- provider: script
  script: bash docker_push.sh
  on:
    branch: develop

- provider: script
  script: bash docker_push.sh $TRAVIS_TAG
  on:
    tags: true
